services:
  - type: web
    name: necropop
    env: python
    rootDir: backend
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    web: gunicorn app.main:app --workers 2 --threads 4 --timeout 120
    startCommand: |
         gunicorn app.main:app --workers 2 --threads 4 --timeout 120
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: DEBUG_LLM
        value: "0"
